apiVersion: v1
kind: Service
metadata:
  name: {{ include "ingress.fullname" . }}-controller
  labels:
    app: {{ include "ingress.fullname" . }}-controller
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: {{ include "ingress.fullname" . }}-controller
