{{- if eq .Values.keepalived.enable true }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ingress.fullname" . }}-keepalived
data:
  {{ .Values.keepalived.vip }}: {{ .Release.Namespace }}/{{ include "ingress.fullname" . }}-controller:{{ .Values.keepalived.lvsmode }}
  {{- end }}

